### ISSUE TITLE
If we only have one chapter, should we reformat?

### ISSUE THREAD

**Issue by mhoemmen** [cpp-linear-algebra/prior-art#3]
@jayeshbadwaik Do we plan on adding more chapters to this document?  If not, may I reformat so that "chapters" become "sections" (and on down the hierarchy)?

**Comment by jayeshbadwaik** [comment]
I do not know of any plans to add more chapters, as such, feel free to modify the document as you like.  Also, I'm not really writing the doc or qualified to write it, I just happen to have admin rights. :-)

**Comment by mhoemmen** [comment]
@jayeshbadwaik I appreciate your admin work and conversion to LaTeX :-) .  I will go ahead and reformat then.  I think it will make things easier.  It's likely that we will get some new coauthors and (sub)sections, but I haven't seen any offers to add new chapters.

**Comment by jayeshbadwaik** [comment]
You're welcome. :-)
