### ISSUE TITLE
Resolve issues related to numpy.

### ISSUE THREAD

**Issue by jayeshbadwaik** [cpp-linear-algebra/prior-art#8]
Resolve issues made about comments [here](https://github.com/cpp-linear-algebra/prior-art/pull/5#discussion_r248752498)

**Comment by mhoemmen** [comment]
Summary of discussion:

  - Python 3's C API has a [Buffer protocol](https://docs.python.org/3/c-api/buffer.html) that could be used to access multidimensional arrays.
  - Numpy builds on top of the Buffer protocol.
  - However, Python 3 does not have multidimensional arrays in the Python language.

@mbrucher , please feel welcome to correct any mistakes here.  Thanks!

**Comment by mbrucher** [comment]
I think what you wrote is fine. I tend to want to be too precise, and it defeats the general purpose. What you wrote is far better than anything else I could come up with and sums up the situation far better.

**Comment by mhoemmen** [comment]
@mbrucher Thanks!  I'll add a new PR with this phrasing.

**Comment by mhoemmen** [comment]
I can see @jayeshbadwaik is working hard right now -- thanks for your revisions! :D  I'll fetch again and check this phrasing.

**Comment by mhoemmen** [comment]
I just put up a PR that implements these changes: https://github.com/cpp-linear-algebra/prior-art/pull/10

**Comment by mhoemmen** [comment]
Thanks! :D
